---


- name: copy the the kubernetes repo(Redhat)
  copy:
    src: "kubernetes.repo"
    dest: "/etc/yum.repos.d/kube.repo"
    owner: "root"
    mode: 0755
  when: ansible_distribution == "Redhat"

- name: copy the the kubernetes repo(Debian)
  template:
    src: "docker.list.j2"
    dest: "/etc/apt/sources.list.d/docker.list"
    owner: "root"
    mode: 0755
  when: ansible_distribution == "Debian"

- name: install yum-utls
  yum:
    name: yum-utils.noarch
    state: present
  when: ansible_distribution == "Redhat"

- name: install yum-utls
  yum:
    name: yum-utils.noarch
    state: present
  when: ansible_distribution == "Redhat" 

- name: create docker-ce repo (Redhat)
  shell: yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  when: ansible_distribution == "Redhat" 
